// ── AUTO-GENERATED by novaboot-scanner ── DO NOT EDIT ──
// Generated at compile time by scanning components.

#include "novaboot/di/di.h"
#include "novaboot/core/server.h"
#include "/home/uday/Projects/novaboot/include/novaboot/data/data_module.h"

using namespace novaboot::di;
using namespace novaboot::data;

// ── Compile-time validation ──────────────────────────────────────────────

// ── Registration function ────────────────────────────────────────────────
void novaboot_di_register_all(novaboot::di::RootContainer& root) {
    (void)root;
}

void novaboot_web_register_all(novaboot::Server& app) {
#ifdef __cpp_impl_reflection
#else
    (void)app;
#endif
}
