#include "novaboot/net/tls_tcp_stream.h"
#include <openssl/err.h>
#include <openssl/ssl.h>
#include <spdlog/spdlog.h>

namespace novaboot::net {

TlsTcpStream::TlsTcpStream(int fd, SSL_CTX* ssl_ctx, bool is_server, const std::string& host) : fd_(fd) {
    ssl_ = ::SSL_new(ssl_ctx);
    if (!ssl_) {
        spdlog::error("SSL_new failed");
        handshake_status_ = HandshakeStatus::Failed;
        return;
    }

    rbio_ = ::BIO_new(::BIO_s_mem());
    wbio_ = ::BIO_new(::BIO_s_mem());
    if (!rbio_ || !wbio_) {
        spdlog::error("BIO_new failed");
        if (rbio_) ::BIO_free(rbio_);
        if (wbio_) ::BIO_free(wbio_);
        ::SSL_free(ssl_);
        ssl_ = nullptr;
        rbio_ = nullptr;
        wbio_ = nullptr;
        handshake_status_ = HandshakeStatus::Failed;
        return;
    }

    // Set non-blocking memory BIO behavior
    ::BIO_set_mem_eof_return(rbio_, -1);
    ::BIO_set_mem_eof_return(wbio_, -1);

    // SSL_set_bio transfers ownership of BIOs to SSL object
    ::SSL_set_bio(ssl_, rbio_, wbio_);
    
    if (is_server) {
        ::SSL_set_accept_state(ssl_);
    } else {
        ::SSL_set_connect_state(ssl_);
        if (!host.empty()) {
            ::SSL_set_tlsext_host_name(ssl_, host.c_str());
            ::SSL_set1_host(ssl_, host.c_str());
        }
    }
}

TlsTcpStream::~TlsTcpStream() {
    if (ssl_) {
        // BIOs are freed automatically by SSL_free
        ::SSL_free(ssl_);
    }
}

TlsTcpStream::TlsTcpStream(TlsTcpStream&& other) noexcept
    : fd_(other.fd_),
      ssl_(other.ssl_),
      rbio_(other.rbio_),
      wbio_(other.wbio_),
      handshake_status_(other.handshake_status_) {
    other.fd_ = -1;
    other.ssl_ = nullptr;
    other.rbio_ = nullptr;
    other.wbio_ = nullptr;
}

TlsTcpStream& TlsTcpStream::operator=(TlsTcpStream&& other) noexcept {
    if (this != &other) {
        if (ssl_) ::SSL_free(ssl_);
        fd_ = other.fd_;
        ssl_ = other.ssl_;
        rbio_ = other.rbio_;
        wbio_ = other.wbio_;
        handshake_status_ = other.handshake_status_;
        other.fd_ = -1;
        other.ssl_ = nullptr;
        other.rbio_ = nullptr;
        other.wbio_ = nullptr;
    }
    return *this;
}

std::string_view TlsTcpStream::negotiated_alpn() const noexcept {
    if (!ssl_) return {};
    const unsigned char* alpn = nullptr;
    unsigned int len = 0;
    ::SSL_get0_alpn_selected(ssl_, &alpn, &len);
    if (alpn) {
        return {reinterpret_cast<const char*>(alpn), len};
    }
    return {};
}

std::expected<TlsTcpStream::TlsData, int> TlsTcpStream::feed_network_data(std::span<const uint8_t> data) {
    if (!ssl_ || handshake_status_ == HandshakeStatus::Failed) {
        return std::unexpected(-1);
    }

    if (!data.empty()) {
        int nwritten = ::BIO_write(rbio_, data.data(), static_cast<int>(data.size()));
        if (nwritten <= 0) {
            spdlog::error("BIO_write failed");
            return std::unexpected(-2);
        }
    }

    TlsData result;

    if (handshake_status_ == HandshakeStatus::Handshaking) {
        auto status = do_handshake(result.handshake_send_data);
        if (!status) {
            return std::unexpected(status.error());
        }
    }

    if (handshake_status_ == HandshakeStatus::Complete) {
        uint8_t buf[4096];
        while (true) {
            int nread = ::SSL_read(ssl_, buf, sizeof(buf));
            if (nread > 0) {
                result.decrypted_app_data.insert(result.decrypted_app_data.end(), buf, buf + nread);
            } else {
                int err = ::SSL_get_error(ssl_, nread);
                if (err == SSL_ERROR_WANT_READ || err == SSL_ERROR_WANT_WRITE) {
                    break; // normal non-blocking yield
                }
                spdlog::warn("SSL_read error: {}", err);
                return std::unexpected(err);
            }
        }
    }

    return result;
}

std::expected<std::vector<uint8_t>, int> TlsTcpStream::encrypt_app_data(std::span<const uint8_t> data) {
    if (!ssl_ || handshake_status_ != HandshakeStatus::Complete) {
        return std::unexpected(-1);
    }

    if (!data.empty()) {
        int nwritten = ::SSL_write(ssl_, data.data(), static_cast<int>(data.size()));
        if (nwritten <= 0) {
            int err = ::SSL_get_error(ssl_, nwritten);
            spdlog::error("SSL_write failed: {}", err);
            return std::unexpected(err);
        }
    }

    return get_pending_send_data();
}

std::expected<TlsTcpStream::HandshakeStatus, int> TlsTcpStream::do_handshake(std::vector<uint8_t>& out_network_data) {
    if (!ssl_) {
        return std::unexpected(-1);
    }

    int ret = ::SSL_do_handshake(ssl_);
    int err = SSL_ERROR_NONE;
    if (ret != 1) {
        err = ::SSL_get_error(ssl_, ret);
    }

    // Read any handshake flight generated by OpenSSL
    std::vector<uint8_t> pending = get_pending_send_data();
    out_network_data.insert(out_network_data.end(), pending.begin(), pending.end());

    if (ret == 1) {
        handshake_status_ = HandshakeStatus::Complete;
        spdlog::debug("TCP TLS handshake complete on fd {}. ALPN selected: {}", fd_, negotiated_alpn());
        return HandshakeStatus::Complete;
    }

    if (err == SSL_ERROR_WANT_READ || err == SSL_ERROR_WANT_WRITE) {
        handshake_status_ = HandshakeStatus::Handshaking;
        return HandshakeStatus::Handshaking;
    }

    spdlog::error("TCP TLS handshake failed on fd {} with error {}", fd_, err);
    handshake_status_ = HandshakeStatus::Failed;
    return std::unexpected(err);
}

std::vector<uint8_t> TlsTcpStream::get_pending_send_data() {
    std::vector<uint8_t> data;
    if (!wbio_) return data;

    uint8_t buf[4096];
    while (true) {
        int nread = ::BIO_read(wbio_, buf, sizeof(buf));
        if (nread > 0) {
            data.insert(data.end(), buf, buf + nread);
        } else {
            break;
        }
    }
    return data;
}

} // namespace novaboot::net
