#pragma once

#include <memory>
#include <stdexcept>
#include <string>
#include <string_view>

#include "novaboot/client/rest_client.h"
#include "novaboot/core/event_loop.h"
#include "novaboot/http3/client_response.h"
#include "novaboot/router/json.h"
#include "novaboot/router/web_attributes.h"

#ifdef __cpp_impl_reflection
#  include <meta>
#endif

namespace novaboot::client {

namespace detail {

/// Parse scheme, host, port from a URL like "https://hostname:4433"
struct ParsedUrl {
    std::string host;
    std::string ip;
    uint16_t    port = 443;
    bool        verify_ssl = true;
};

inline ParsedUrl parse_url(std::string_view url) {
    ParsedUrl result;

    // Strip "https://"
    if (url.starts_with("https://")) {
        url.remove_prefix(8);
    } else if (url.starts_with("http://")) {
        url.remove_prefix(7);
        result.verify_ssl = false; // HTTP over QUIC (unusual but handle it)
    }

    // Split host:port
    auto colon = url.rfind(':');
    if (colon != std::string_view::npos) {
        result.host = std::string(url.substr(0, colon));
        try {
            result.port = static_cast<uint16_t>(
                std::stoul(std::string(url.substr(colon + 1))));
        } catch (...) {
            result.port = 443;
        }
    } else {
        result.host = std::string(url);
        result.port = 443;
    }
    return result;
}

/// Build a RestClient::Config from a URL string.
inline RestClient::Config config_from_url(std::string_view url) {
    auto parsed = parse_url(url);
    RestClient::Config cfg;
    cfg.host       = parsed.host;
    cfg.port       = parsed.port;
    cfg.verify_ssl = parsed.verify_ssl;
    return cfg;
}

#ifdef __cpp_impl_reflection

/// Checks if a method on a rest_client interface has a GET/POST/etc. annotation
/// and returns the path string, otherwise returns empty.
template<std::meta::info m>
consteval std::string_view get_method_path(auto annotation_type) {
    auto anns = std::meta::annotations_of_with_type(m, annotation_type);
    if (anns.empty()) return "";
    return std::meta::extract<typename[:annotation_type:]>(anns[0]).path;
}

/// Substitute {param} placeholders in a path template with actual argument values.
/// e.g. "/api/users/{id}" + id=42 → "/api/users/42"
///
/// This runs at runtime — simple linear scan.
inline std::string substitute_path_params(
    std::string path_template,
    const std::vector<std::pair<std::string, std::string>>& params) {

    for (const auto& [name, value] : params) {
        std::string placeholder = "{" + name + "}";
        size_t pos = path_template.find(placeholder);
        while (pos != std::string::npos) {
            path_template.replace(pos, placeholder.size(), value);
            pos = path_template.find(placeholder, pos + value.size());
        }
    }
    return path_template;
}

#endif // __cpp_impl_reflection

} // namespace detail

/// Factory that instantiates a scanner-generated concrete implementation of a
/// `rest_client`-annotated interface T.
///
/// The novaboot-scanner tool reads T's header at build time and emits a sidecar
/// "name.client.h" containing class TImpl : public T { ... } that overrides
/// every pure virtual method with the real HTTP call.  make<T>() reads T's
/// [[=novaboot::web::rest_client{url, proto}]] annotation at compile time, opens
/// the connection, and returns a unique_ptr<T> pointing at TImpl.
///
/// Example interface:
///   class [[=novaboot::web::rest_client{"https://localhost:4433","http2"}]] UserServiceClient {
///   public:
///       [[=novaboot::web::get{"/api/users/{id}"}]]
///       virtual novaboot::ResponseEntity<User> get_user(int id) = 0;
///   };
///
/// Generated sidecar (user_service_client.client.h):
///   class UserServiceClientImpl : public UserServiceClient { ... };
///
/// Usage in client code:
///   #include "client/user_service_client.client.h"
///   auto client = novaboot::client::RestClientFactory::make<UserServiceClient,
///                                                           UserServiceClientImpl>(event_loop);
///   auto resp = client->get_user(42);
///
class RestClientFactory {
public:
    /// Create a connected implementation of the `rest_client`-annotated interface T.
    ///
    /// TImpl must be a concrete subclass of T (generated by novaboot-scanner)
    /// that is constructible from a unique_ptr<RestClient>.
    ///
    /// The URL and protocol are read from T's [[=novaboot::web::rest_client{...}]]
    /// annotation at compile time.
    template<typename T, typename TImpl>
    static std::unique_ptr<T> make(core::EventLoop& event_loop) {
#ifdef __cpp_impl_reflection
        constexpr auto cls = ^^T;

        static_assert(
            !std::meta::annotations_of_with_type(cls, ^^novaboot::web::rest_client).empty(),
            "RestClientFactory::make<T,TImpl>() requires T to be annotated with "
            "[[=novaboot::web::rest_client{\"https://host:port\"}]]");

        constexpr auto ann = std::meta::annotations_of_with_type(
            cls, ^^novaboot::web::rest_client)[0];
        static constexpr auto annot = std::meta::extract<novaboot::web::rest_client>(ann);
        static constexpr std::string_view url      = annot.url;
        static constexpr std::string_view protocol = annot.protocol;

        auto cfg = detail::config_from_url(url);
        if (protocol == "http1.1") {
            cfg.protocol = Protocol::HTTP1_1;
        } else if (protocol == "http2") {
            cfg.protocol = Protocol::HTTP2;
        } else {
            cfg.protocol = Protocol::HTTP3;
        }

        // TImpl is the scanner-generated concrete class; it takes ownership of
        // the RestClient connection and overrides all of T's pure virtuals.
        return std::make_unique<TImpl>(RestClient::create(cfg, event_loop));
#else
        (void)event_loop;
        throw std::runtime_error(
            "RestClientFactory::make<T,TImpl>() requires C++26 reflection "
            "(compile with -freflection)");
        return nullptr;
#endif
    }
};

/// Convenience free function wrapper.
template<typename T, typename TImpl>
std::unique_ptr<T> make_rest_client(core::EventLoop& event_loop) {
    return RestClientFactory::make<T, TImpl>(event_loop);
}

} // namespace novaboot::client
