#pragma once
#include <string>
#include <string_view>
#include <vector>
#include <variant>
#include <memory>
#include <optional>
#include <cstdint>

namespace novaboot::db {

/// Database bind parameter type variant
using Parameter = std::variant<
    std::nullptr_t,
    std::int64_t,
    double,
    std::string,
    std::vector<std::uint8_t>,
    bool
>;

/// Abstract Row Result Set
class ResultSet {
public:
    virtual ~ResultSet() = default;

    /// Advance to the next row. Returns false when no more rows exist.
    virtual bool next() = 0;

    /// Check if the column is null
    virtual bool is_null(int col_index) = 0;

    /// Get column value by index
    virtual std::int64_t get_int(int col_index) = 0;
    virtual double get_double(int col_index) = 0;
    virtual std::string get_string(int col_index) = 0;
    virtual std::vector<std::uint8_t> get_blob(int col_index) = 0;
    virtual bool get_bool(int col_index) = 0;

    /// Get metadata info
    virtual int column_count() const = 0;
    virtual std::string_view column_name(int col_index) const = 0;
};

/// Abstract Connection Session
class Connection {
public:
    virtual ~Connection() = default;

    /// Execute write queries (INSERT, UPDATE, DELETE, CREATE TABLE)
    virtual void execute(std::string_view sql, const std::vector<Parameter>& params = {}) = 0;

    /// Execute read queries (SELECT) returning a ResultSet
    virtual std::unique_ptr<ResultSet> query(std::string_view sql, const std::vector<Parameter>& params = {}) = 0;

    /// Get the ID generated by the last INSERT operation
    virtual std::int64_t last_insert_id() = 0;

    /// Transaction Controls
    virtual void begin_transaction() = 0;
    virtual void commit() = 0;
    virtual void rollback() = 0;
};

/// Abstract connection pool (DataSource)
class DataSource {
public:
    virtual ~DataSource() = default;

    /// Retrieve an active connection from the pool
    virtual std::shared_ptr<Connection> get_connection() = 0;

    /// Graceful shutdown
    virtual void close() = 0;
};

} // namespace novaboot::db
