# ─── NovaBoot DI Component Scanner (CMake Codegen) ───────────────────────────
#
# This CMake module provides the novaboot_di_scan() macro which generates a
# C++ registration file from a list of annotated component types.
#
# Usage in CMakeLists.txt:
#
#   include(cmake/ComponentScan.cmake)
#
#   novaboot_di_scan(
#       TARGET      myapp
#       OUTPUT_FILE ${CMAKE_CURRENT_BINARY_DIR}/di_registrations.cpp
#       COMPONENTS
#           UserService
#           UserRepository
#           PaymentService
#           RequestLogger
#       INCLUDE_HEADERS
#           "myapp/services/user_service.h"
#           "myapp/repos/user_repository.h"
#           "myapp/services/payment_service.h"
#           "myapp/middleware/request_logger.h"
#   )
#
#   target_sources(myapp PRIVATE ${CMAKE_CURRENT_BINARY_DIR}/di_registrations.cpp)
#
# The generated file contains:
#   - A novaboot_di_register_all(novaboot::di::RootContainer&) function
#     that registers all listed components based on their reflection annotations.
#
# Requirements:
#   - GCC 16+ with -freflection
#   - All component types must be annotated with [[=novaboot::di::component{}]]
#     or a stereotype alias.

cmake_minimum_required(VERSION 3.25)

# ─── novaboot_di_scan ─────────────────────────────────────────────────────────
#
# Generates a C++ file that registers all annotated components.
#
# Arguments:
#   TARGET        - CMake target to attach the generated file to
#   OUTPUT_FILE   - Absolute path for the generated .cpp file
#   COMPONENTS    - List of C++ type names to register
#   INCLUDE_HEADERS - List of header files to include in the generated file
#
macro(novaboot_di_scan)
    cmake_parse_arguments(DI_SCAN
        ""                              # options (none)
        "TARGET;OUTPUT_FILE"            # single-value
        "COMPONENTS;INCLUDE_HEADERS"    # multi-value
        ${ARGN}
    )

    if(NOT DI_SCAN_TARGET)
        message(FATAL_ERROR "novaboot_di_scan: TARGET is required")
    endif()
    if(NOT DI_SCAN_OUTPUT_FILE)
        message(FATAL_ERROR "novaboot_di_scan: OUTPUT_FILE is required")
    endif()
    if(NOT DI_SCAN_COMPONENTS)
        message(WARNING "novaboot_di_scan: No COMPONENTS specified, generated file will be empty")
    endif()

    # Build the generated file content
    set(_gen_content "// ── AUTO-GENERATED by novaboot_di_scan() ── DO NOT EDIT ──\n")
    string(APPEND _gen_content "// Generated at cmake configure time.\n")
    string(APPEND _gen_content "// Registers all [[=novaboot::di::component{}]]-annotated types.\n\n")
    string(APPEND _gen_content "#include \"novaboot/di/di.h\"\n")

    foreach(_header ${DI_SCAN_INCLUDE_HEADERS})
        string(APPEND _gen_content "#include \"${_header}\"\n")
    endforeach()

    string(APPEND _gen_content "\nusing namespace novaboot::di;\n\n")
    string(APPEND _gen_content "// ── Compile-time validation ──────────────────────────────────────────────\n")
    string(APPEND _gen_content "#ifdef __cpp_impl_reflection\n")

    foreach(_comp ${DI_SCAN_COMPONENTS})
        string(APPEND _gen_content
            "static_assert(novaboot::di::detail::is_managed_component(^^${_comp}),\n"
            "    \"${_comp} must be annotated with [[=novaboot::di::component{}]] or a stereotype alias\");\n"
        )
    endforeach()

    string(APPEND _gen_content "#endif // __cpp_impl_reflection\n\n")

    string(APPEND _gen_content
        "// ── Registration function ────────────────────────────────────────────────\n"
        "// Call this from your Server builder or main() before root.build().\n"
        "void novaboot_di_register_all(novaboot::di::RootContainer& root) {\n"
        "#ifdef __cpp_impl_reflection\n"
    )

    foreach(_comp ${DI_SCAN_COMPONENTS})
        string(APPEND _gen_content
            "    // ${_comp}\n"
            "    [&]() consteval {\n"
            "        constexpr auto scope     = novaboot::di::detail::get_scope(^^${_comp});\n"
            "        constexpr bool is_lazy   = novaboot::di::detail::is_lazy_bean(^^${_comp});\n"
            "        constexpr bool is_prim   = novaboot::di::detail::is_primary_bean(^^${_comp});\n"
            "        constexpr const char* q  = novaboot::di::detail::get_named_qualifier(^^${_comp});\n"
            "        root.register_bean<${_comp}>(\n"
            "            [](novaboot::di::ContainerBase& c) -> ${_comp}* {\n"
            "                return new ${_comp}{ /* deps resolved via codegen */ };\n"
            "            },\n"
            "            scope, q, is_prim, is_lazy\n"
            "        );\n"
            "    }();\n\n"
        )
    endforeach()

    string(APPEND _gen_content
        "#else\n"
        "    // Fallback: manual registration required without -freflection\n"
        "    (void)root;\n"
        "#endif\n"
        "}\n"
    )

    # Write the generated file
    file(WRITE "${DI_SCAN_OUTPUT_FILE}" "${_gen_content}")

    message(STATUS "novaboot_di_scan: Generated ${DI_SCAN_OUTPUT_FILE} with ${DI_SCAN_COMPONENTS} components")
endmacro()
