#include <iostream>
#include <fstream>
#include <regex>
#include <string>
#include <vector>
#include <filesystem>
#include <algorithm>

#include <unordered_set>

namespace fs = std::filesystem;

struct FieldInfo {
    std::string type;
    std::string name;
};

bool is_primitive_type(const std::string& type) {
    static const std::unordered_set<std::string> primitives = {
        "int", "double", "float", "bool", "char", "size_t", "std::size_t",
        "int64_t", "uint64_t", "int32_t", "uint32_t", "short", "long"
    };
    return primitives.count(type) > 0 || type.back() == '*';
}

std::string generate_to_string_field(const std::string& type, const std::string& name) {
    if (type == "std::string" || type == "string" || type == "std::string_view" || type == "string_view") {
        return name;
    } else if (is_primitive_type(type) && type != "bool") {
        return "std::to_string(" + name + ")";
    } else if (type == "bool") {
        return "(" + name + " ? \"true\" : \"false\")";
    } else {
        return "\"<" + type + ">\"";
    }
}

FieldInfo parse_field(std::string decl) {
    auto eq_pos = decl.find('=');
    if (eq_pos != std::string::npos) {
        decl = decl.substr(0, eq_pos);
    }
    while (!decl.empty() && std::isspace(decl.back())) decl.pop_back();
    while (!decl.empty() && std::isspace(decl.front())) decl.erase(0, 1);
    
    int i = decl.size() - 1;
    while (i >= 0 && (std::isalnum(decl[i]) || decl[i] == '_')) {
        i--;
    }
    std::string name = decl.substr(i + 1);
    std::string type = decl.substr(0, i + 1);
    
    while (!type.empty() && (std::isspace(type.back()) || type.back() == '*' || type.back() == '&')) {
        if (type.back() == '*' || type.back() == '&') {
            break;
        }
        type.pop_back();
    }
    while (!type.empty() && std::isspace(type.front())) type.erase(0, 1);
    while (!type.empty() && std::isspace(type.back())) type.pop_back();
    
    return {type, name};
}

void generate_lombok_header(const std::string& filepath, const std::string& struct_name,
                            const std::vector<FieldInfo>& fields,
                            bool has_getter, bool has_setter, bool has_builder,
                            bool has_tostring, bool has_equals_hash) {
    std::string lowercase_name = struct_name;
    std::transform(lowercase_name.begin(), lowercase_name.end(), lowercase_name.begin(), ::tolower);
    
    fs::path header_path(filepath);
    fs::path output_path = header_path.parent_path() / (lowercase_name + ".lombok.h");
    
    std::ofstream out(output_path);
    if (!out.is_open()) {
        std::cerr << "novaboot-scanner lombok error: Could not write to " << output_path << "\n";
        return;
    }
    out << "// ── AUTO-GENERATED by novaboot-scanner (Lombok Preprocessor) ── DO NOT EDIT ──\n";
    out << "#pragma once\n\n";
    
    out << "    // No-Args Constructor\n";
    out << "    " << struct_name << "() = default;\n\n";
    
    if (!fields.empty()) {
        out << "    // All-Args Constructor\n";
        out << "    " << struct_name << "(\n";
        for (size_t i = 0; i < fields.size(); ++i) {
            out << "        " << fields[i].type << " t_" << fields[i].name;
            if (i + 1 < fields.size()) out << ",\n";
        }
        out << "\n    ) : ";
        for (size_t i = 0; i < fields.size(); ++i) {
            out << fields[i].name << "(std::move(t_" << fields[i].name << "))";
            if (i + 1 < fields.size()) out << ",\n        ";
        }
        out << " {}\n\n";
    }
    
    if (has_getter) {
        out << "    // Getters\n";
        for (const auto& f : fields) {
            if (is_primitive_type(f.type)) {
                out << "    [[nodiscard]] " << f.type << " get_" << f.name << "() const noexcept { return " << f.name << "; }\n";
            } else {
                out << "    [[nodiscard]] const " << f.type << "& get_" << f.name << "() const noexcept { return " << f.name << "; }\n";
                out << "    [[nodiscard]] " << f.type << "& get_" << f.name << "() noexcept { return " << f.name << "; }\n";
            }
        }
        out << "\n";
    }
    
    if (has_setter) {
        out << "    // Setters\n";
        for (const auto& f : fields) {
            out << "    void set_" << f.name << "(" << f.type << " val) noexcept { " << f.name << " = std::move(val); }\n";
        }
        out << "\n";
    }
    
    if (has_builder) {
        out << "    // Builder\n";
        out << "    class Builder {\n";
        out << "    private:\n";
        for (const auto& f : fields) {
            out << "        " << f.type << " " << f.name << "_ = {};\n";
        }
        out << "\n    public:\n";
        out << "        Builder() = default;\n\n";
        for (const auto& f : fields) {
            out << "        Builder& " << f.name << "(" << f.type << " val) {\n";
            out << "            " << f.name << "_ = std::move(val);\n";
            out << "            return *this;\n";
            out << "        }\n\n";
        }
        out << "        " << struct_name << " build() const {\n";
        out << "            " << struct_name << " obj;\n";
        for (const auto& f : fields) {
            out << "            obj." << f.name << " = " << f.name << "_;\n";
        }
        out << "            return obj;\n";
        out << "        }\n";
        out << "    };\n\n";
        out << "    static Builder builder() { return Builder{}; }\n\n";
    }
    
    if (has_tostring) {
        out << "    // ToString\n";
        out << "    [[nodiscard]] std::string to_string() const {\n";
        out << "        return std::string(\"" << struct_name << "(\")";
        for (size_t i = 0; i < fields.size(); ++i) {
            out << "\n            + \"" << fields[i].name << "=\" + ";
            out << generate_to_string_field(fields[i].type, fields[i].name);
            if (i + 1 < fields.size()) {
                out << " + \", \"";
            }
        }
        out << " + \")\";\n";
        out << "    }\n\n";
    }
    
    if (has_equals_hash) {
        out << "    // Equals & HashCode\n";
        out << "    bool operator==(const " << struct_name << "& other) const noexcept {\n";
        if (fields.empty()) {
            out << "        return true;\n";
        } else {
            out << "        return ";
            for (size_t i = 0; i < fields.size(); ++i) {
                out << fields[i].name << " == other." << fields[i].name;
                if (i + 1 < fields.size()) out << "\n            && ";
            }
            out << ";\n";
        }
        out << "    }\n\n";
        
        out << "    bool operator!=(const " << struct_name << "& other) const noexcept {\n";
        out << "        return !(*this == other);\n";
        out << "    }\n\n";
        
        out << "    [[nodiscard]] std::size_t hash_code() const noexcept {\n";
        out << "        std::size_t h = 0;\n";
        out << "        auto combine = [](std::size_t& seed, const auto& val) {\n";
        out << "            seed ^= std::hash<std::decay_t<decltype(val)>>{}(val) + 0x9e3779b9 + (seed << 6) + (seed >> 2);\n";
        out << "        };\n";
        for (const auto& f : fields) {
            out << "        combine(h, " << f.name << ");\n";
        }
        out << "        return h;\n";
        out << "    }\n";
    }
    
    std::cout << "novaboot-scanner lombok: Generated sidecar header " << output_path << "\n";
}

void process_lombok(const std::string& filepath, const std::string& content) {
    std::regex lombok_class_regex(
        R"((?:(struct|class)\s+)?\[\[\s*=\s*(?:novaboot\s*::\s*)?lombok\s*::\s*(data|builder|getter|setter)\s*\{?\}?\s*\]\](?:\s|\[\[[^\]]*\]\]|/\*[^*]*\*/|//[^\n]*\n)*(?:(struct|class)\s+)?([a-zA-Z_][a-zA-Z0-9_]*)\s*\{)"
    );
    
    auto words_begin = std::sregex_iterator(content.begin(), content.end(), lombok_class_regex);
    auto words_end = std::sregex_iterator();
    
    for (std::sregex_iterator i = words_begin; i != words_end; ++i) {
        std::smatch match = *i;
        std::string full_match = match[0].str();
        std::string struct_name = match[4].str();
        
        bool has_data = (full_match.find("data") != std::string::npos);
        bool has_builder = (full_match.find("builder") != std::string::npos) || has_data;
        bool has_getter = (full_match.find("getter") != std::string::npos) || has_data;
        bool has_setter = (full_match.find("setter") != std::string::npos) || has_data;
        bool has_tostring = has_data;
        bool has_equals_hash = has_data;
        
        size_t start_pos = match.position(0) + match.length();
        int brace_count = 1;
        size_t end_pos = start_pos;
        while (end_pos < content.size() && brace_count > 0) {
            if (content[end_pos] == '{') brace_count++;
            else if (content[end_pos] == '}') brace_count--;
            end_pos++;
        }
        
        if (brace_count > 0) {
            std::cerr << "novaboot-scanner lombok error: Mismatched braces for struct " << struct_name << " in " << filepath << "\n";
            continue;
        }
        
        std::string body = content.substr(start_pos, (end_pos - 1) - start_pos);
        
        std::vector<FieldInfo> fields;
        std::vector<std::string> decls;
        
        size_t last_pos = 0;
        size_t pos = 0;
        while ((pos = body.find(';', last_pos)) != std::string::npos) {
            decls.push_back(body.substr(last_pos, pos - last_pos));
            last_pos = pos + 1;
        }
        
        for (auto& decl : decls) {
            decl = std::regex_replace(decl, std::regex(R"(//[^\n]*)"), "");
            decl = std::regex_replace(decl, std::regex(R"(/\*.*?\*/)", std::regex_constants::extended), "");
            decl = std::regex_replace(decl, std::regex(R"(\[\[[^\]]*\]\])"), "");
            
            while (!decl.empty() && std::isspace(decl.back())) decl.pop_back();
            while (!decl.empty() && std::isspace(decl.front())) decl.erase(0, 1);
            
            if (decl.empty()) continue;
            if (decl[0] == '#') continue;
            if (decl.find('(') != std::string::npos || decl.find(')') != std::string::npos) continue;
            
            static const std::vector<std::string> skip_keywords = {
                "using", "typedef", "friend", "public:", "private:", "protected:", "class", "struct", "enum"
            };
            bool skip = false;
            for (const auto& keyword : skip_keywords) {
                if (decl.find(keyword) != std::string::npos) {
                    skip = true;
                    break;
                }
            }
            if (skip) continue;
            
            FieldInfo f = parse_field(decl);
            if (!f.name.empty() && !f.type.empty()) {
                fields.push_back(f);
            }
        }
        
        generate_lombok_header(filepath, struct_name, fields, has_getter, has_setter, has_builder, has_tostring, has_equals_hash);
    }
}

struct ComponentInfo {
    std::string name;
    std::string filepath;
    std::string stereotype;
};

int main(int argc, char* argv[]) {
    std::vector<std::string> scan_dirs;
    std::string output_file = "di_registrations.cpp";

    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if ((arg == "--dir" || arg == "-d") && i + 1 < argc) {
            scan_dirs.push_back(argv[++i]);
        } else if ((arg == "--output" || arg == "-o") && i + 1 < argc) {
            output_file = argv[++i];
        }
    }
    if (scan_dirs.empty()) {
        scan_dirs.push_back(".");
    }

    std::vector<ComponentInfo> components;

    // Regex to match component annotations and extract class name:
    // Matches [[=novaboot::di::component{}]] or [[=component{}]] etc.
    // then handles optional whitespace, other annotations, comments, newlines
    // and finally struct/class Name
    std::regex component_regex(
        R"((?:(struct|class)\s+)?\[\[\s*=\s*(?:[a-zA-Z0-9_]+\s*::\s*)*(component|service|repository|controller_advice|rest_controller|controller|module_tag|sql_repository|cache_repository)\s*(?:\{[^{}]*\})?\s*\]\](?:\s|\[\[[^\]]*\]\]|/\*[^*]*\*/|//[^\n]*\n)*(?:(struct|class)\s+)?([a-zA-Z_][a-zA-Z0-9_]*))"
    );

    try {
        for (const auto& scan_dir : scan_dirs) {
            // Recursively walk the directory
            for (const auto& entry : fs::recursive_directory_iterator(scan_dir)) {
                if (!entry.is_regular_file()) continue;

                auto ext = entry.path().extension();
                if (ext == ".h" || ext == ".hpp" || ext == ".hxx" || ext == ".cpp" || ext == ".cc") {
                    // Read file content
                    std::ifstream file(entry.path());
                    if (!file.is_open()) continue;

                    std::string content((std::istreambuf_iterator<char>(file)),
                                         std::istreambuf_iterator<char>());

                    process_lombok(fs::absolute(entry.path()).string(), content);

                    auto words_begin = std::sregex_iterator(content.begin(), content.end(), component_regex);
                    auto words_end = std::sregex_iterator();

                    for (std::sregex_iterator i = words_begin; i != words_end; ++i) {
                        std::smatch match = *i;
                        std::string name = match[4].str();
                        std::string stereotype = match[2].str();
                        components.push_back({name, fs::absolute(entry.path()).string(), stereotype});
                    }
                }
            }
        }
    } catch (const std::exception& e) {
        std::cerr << "novaboot-scanner error: " << e.what() << "\n";
        return 1;
    }

    // Write output registrations file
    std::ofstream out(output_file);
    if (!out.is_open()) {
        std::cerr << "Failed to open output file: " << output_file << "\n";
        return 1;
    }

    out << "// ── AUTO-GENERATED by novaboot-scanner ── DO NOT EDIT ──\n";
    out << "// Generated at compile time by scanning components.\n\n";
    out << "#include \"novaboot/di/di.h\"\n";
    out << "#include \"novaboot/core/server.h\"\n";

    // Deduplicate headers
    std::vector<std::string> headers;
    for (const auto& comp : components) {
        if (std::find(headers.begin(), headers.end(), comp.filepath) == headers.end()) {
            headers.push_back(comp.filepath);
        }
    }

    for (const auto& header : headers) {
        out << "#include \"" << header << "\"\n";
    }

    out << "\nusing namespace novaboot::di;\n";
    out << "using namespace novaboot::data;\n\n";
    out << "// ── Compile-time validation ──────────────────────────────────────────────\n";
    out << "#ifdef __cpp_impl_reflection\n";
    for (const auto& comp : components) {
        if (comp.stereotype == "module_tag") {
            out << "static_assert(novaboot::di::detail::is_module_class(^^" << comp.name << "),\n";
            out << "    \"" << comp.name << " must be annotated with [[=novaboot::di::module_tag{}]]\");\n";
        } else {
            out << "static_assert(novaboot::di::detail::is_managed_component(^^" << comp.name << "),\n";
            out << "    \"" << comp.name << " must be annotated with [[=novaboot::di::component{}]] or a stereotype alias\");\n";
        }
    }
    out << "#endif // __cpp_impl_reflection\n\n";

    out << "// ── Registration function ────────────────────────────────────────────────\n";
    out << "void novaboot_di_register_all(novaboot::di::RootContainer& root) {\n";
    out << "#ifdef __cpp_impl_reflection\n";
    for (const auto& comp : components) {
        out << "    // " << comp.name << "\n";
        if (comp.stereotype == "module_tag") {
            out << "    register_module<" << comp.name << ">(root);\n\n";
        } else {
            out << "    root.register_component<" << comp.name << ">();\n\n";
        }
    }
    out << "#else\n";
    out << "    (void)root;\n";
    out << "#endif\n";
    out << "}\n\n";

    out << "void novaboot_web_register_all(novaboot::Server& app) {\n";
    out << "#ifdef __cpp_impl_reflection\n";
    for (const auto& comp : components) {
        if (comp.stereotype == "controller" || comp.stereotype == "rest_controller") {
            out << "    app.register_controller<" << comp.name << ">();\n";
        } else if (comp.stereotype == "controller_advice") {
            out << "    app.register_advice<" << comp.name << ">();\n";
        }
    }
    out << "#else\n";
    out << "    (void)app;\n";
    out << "#endif\n";
    out << "}\n";

    std::cout << "novaboot-scanner: Scanned " << scan_dirs.size() << " directories, found " << components.size() << " components, wrote to " << output_file << "\n";
    return 0;
}
