#include <iostream>
#include <fstream>
#include <regex>
#include <string>
#include <vector>
#include <filesystem>
#include <algorithm>

#include <unordered_set>

namespace fs = std::filesystem;

struct FieldInfo {
    std::string type;
    std::string name;
};

bool is_primitive_type(const std::string& type) {
    static const std::unordered_set<std::string> primitives = {
        "int", "double", "float", "bool", "char", "size_t", "std::size_t",
        "int64_t", "uint64_t", "int32_t", "uint32_t", "short", "long"
    };
    return primitives.count(type) > 0 || type.back() == '*';
}

std::string generate_to_string_field(const std::string& type, const std::string& name) {
    if (type == "std::string" || type == "string" || type == "std::string_view" || type == "string_view") {
        return name;
    } else if (is_primitive_type(type) && type != "bool") {
        return "std::to_string(" + name + ")";
    } else if (type == "bool") {
        return "(" + name + " ? \"true\" : \"false\")";
    } else {
        return "\"<" + type + ">\"";
    }
}

FieldInfo parse_field(std::string decl) {
    auto eq_pos = decl.find('=');
    if (eq_pos != std::string::npos) {
        decl = decl.substr(0, eq_pos);
    }
    while (!decl.empty() && std::isspace(decl.back())) decl.pop_back();
    while (!decl.empty() && std::isspace(decl.front())) decl.erase(0, 1);
    
    int i = decl.size() - 1;
    while (i >= 0 && (std::isalnum(decl[i]) || decl[i] == '_')) {
        i--;
    }
    std::string name = decl.substr(i + 1);
    std::string type = decl.substr(0, i + 1);
    
    while (!type.empty() && (std::isspace(type.back()) || type.back() == '*' || type.back() == '&')) {
        if (type.back() == '*' || type.back() == '&') {
            break;
        }
        type.pop_back();
    }
    while (!type.empty() && std::isspace(type.front())) type.erase(0, 1);
    while (!type.empty() && std::isspace(type.back())) type.pop_back();
    
    return {type, name};
}

void generate_lombok_header(const std::string& filepath, const std::string& struct_name,
                            const std::vector<FieldInfo>& fields,
                            bool has_getter, bool has_setter, bool has_builder,
                            bool has_tostring, bool has_equals_hash) {
    std::string lowercase_name = struct_name;
    std::transform(lowercase_name.begin(), lowercase_name.end(), lowercase_name.begin(), ::tolower);
    
    fs::path header_path(filepath);
    fs::path output_path = header_path.parent_path() / (lowercase_name + ".lombok.h");
    
    std::ofstream out(output_path);
    if (!out.is_open()) {
        std::cerr << "novaboot-scanner lombok error: Could not write to " << output_path << "\n";
        return;
    }
    out << "// ── AUTO-GENERATED by novaboot-scanner (Lombok Preprocessor) ── DO NOT EDIT ──\n";
    out << "#pragma once\n\n";
    
    out << "    // No-Args Constructor\n";
    out << "    " << struct_name << "() = default;\n\n";
    
    if (!fields.empty()) {
        out << "    // All-Args Constructor\n";
        out << "    " << struct_name << "(\n";
        for (size_t i = 0; i < fields.size(); ++i) {
            out << "        " << fields[i].type << " t_" << fields[i].name;
            if (i + 1 < fields.size()) out << ",\n";
        }
        out << "\n    ) : ";
        for (size_t i = 0; i < fields.size(); ++i) {
            out << fields[i].name << "(std::move(t_" << fields[i].name << "))";
            if (i + 1 < fields.size()) out << ",\n        ";
        }
        out << " {}\n\n";
    }
    
    if (has_getter) {
        out << "    // Getters\n";
        for (const auto& f : fields) {
            if (is_primitive_type(f.type)) {
                out << "    [[nodiscard]] " << f.type << " get_" << f.name << "() const noexcept { return " << f.name << "; }\n";
            } else {
                out << "    [[nodiscard]] const " << f.type << "& get_" << f.name << "() const noexcept { return " << f.name << "; }\n";
                out << "    [[nodiscard]] " << f.type << "& get_" << f.name << "() noexcept { return " << f.name << "; }\n";
            }
        }
        out << "\n";
    }
    
    if (has_setter) {
        out << "    // Setters\n";
        for (const auto& f : fields) {
            out << "    void set_" << f.name << "(" << f.type << " val) noexcept { " << f.name << " = std::move(val); }\n";
        }
        out << "\n";
    }
    
    if (has_builder) {
        out << "    // Builder\n";
        out << "    class Builder {\n";
        out << "    private:\n";
        for (const auto& f : fields) {
            out << "        " << f.type << " " << f.name << "_ = {};\n";
        }
        out << "\n    public:\n";
        out << "        Builder() = default;\n\n";
        for (const auto& f : fields) {
            out << "        Builder& " << f.name << "(" << f.type << " val) {\n";
            out << "            " << f.name << "_ = std::move(val);\n";
            out << "            return *this;\n";
            out << "        }\n\n";
        }
        out << "        " << struct_name << " build() const {\n";
        out << "            " << struct_name << " obj;\n";
        for (const auto& f : fields) {
            out << "            obj." << f.name << " = " << f.name << "_;\n";
        }
        out << "            return obj;\n";
        out << "        }\n";
        out << "    };\n\n";
        out << "    static Builder builder() { return Builder{}; }\n\n";
    }
    
    if (has_tostring) {
        out << "    // ToString\n";
        out << "    [[nodiscard]] std::string to_string() const {\n";
        out << "        return std::string(\"" << struct_name << "(\")";
        for (size_t i = 0; i < fields.size(); ++i) {
            out << "\n            + \"" << fields[i].name << "=\" + ";
            out << generate_to_string_field(fields[i].type, fields[i].name);
            if (i + 1 < fields.size()) {
                out << " + \", \"";
            }
        }
        out << " + \")\";\n";
        out << "    }\n\n";
    }
    
    if (has_equals_hash) {
        out << "    // Equals & HashCode\n";
        out << "    bool operator==(const " << struct_name << "& other) const noexcept {\n";
        if (fields.empty()) {
            out << "        return true;\n";
        } else {
            out << "        return ";
            for (size_t i = 0; i < fields.size(); ++i) {
                out << fields[i].name << " == other." << fields[i].name;
                if (i + 1 < fields.size()) out << "\n            && ";
            }
            out << ";\n";
        }
        out << "    }\n\n";
        
        out << "    bool operator!=(const " << struct_name << "& other) const noexcept {\n";
        out << "        return !(*this == other);\n";
        out << "    }\n\n";
        
        out << "    [[nodiscard]] std::size_t hash_code() const noexcept {\n";
        out << "        std::size_t h = 0;\n";
        out << "        auto combine = [](std::size_t& seed, const auto& val) {\n";
        out << "            seed ^= std::hash<std::decay_t<decltype(val)>>{}(val) + 0x9e3779b9 + (seed << 6) + (seed >> 2);\n";
        out << "        };\n";
        for (const auto& f : fields) {
            out << "        combine(h, " << f.name << ");\n";
        }
        out << "        return h;\n";
        out << "    }\n";
    }
    
    std::cout << "novaboot-scanner lombok: Generated sidecar header " << output_path << "\n";
}

void process_lombok(const std::string& filepath, const std::string& content) {
    std::regex lombok_class_regex(
        R"((?:(struct|class)\s+)?\[\[\s*=\s*(?:novaboot\s*::\s*)?lombok\s*::\s*(data|builder|getter|setter)\s*\{?\}?\s*\]\](?:\s|\[\[[^\]]*\]\]|/\*[^*]*\*/|//[^\n]*\n)*(?:(struct|class)\s+)?([a-zA-Z_][a-zA-Z0-9_]*)\s*\{)"
    );
    
    auto words_begin = std::sregex_iterator(content.begin(), content.end(), lombok_class_regex);
    auto words_end = std::sregex_iterator();
    
    for (std::sregex_iterator i = words_begin; i != words_end; ++i) {
        std::smatch match = *i;
        std::string full_match = match[0].str();
        std::string struct_name = match[4].str();
        
        bool has_data = (full_match.find("data") != std::string::npos);
        bool has_builder = (full_match.find("builder") != std::string::npos) || has_data;
        bool has_getter = (full_match.find("getter") != std::string::npos) || has_data;
        bool has_setter = (full_match.find("setter") != std::string::npos) || has_data;
        bool has_tostring = has_data;
        bool has_equals_hash = has_data;
        
        size_t start_pos = match.position(0) + match.length();
        int brace_count = 1;
        size_t end_pos = start_pos;
        while (end_pos < content.size() && brace_count > 0) {
            if (content[end_pos] == '{') brace_count++;
            else if (content[end_pos] == '}') brace_count--;
            end_pos++;
        }
        
        if (brace_count > 0) {
            std::cerr << "novaboot-scanner lombok error: Mismatched braces for struct " << struct_name << " in " << filepath << "\n";
            continue;
        }
        
        std::string body = content.substr(start_pos, (end_pos - 1) - start_pos);
        
        std::vector<FieldInfo> fields;
        std::vector<std::string> decls;
        
        size_t last_pos = 0;
        size_t pos = 0;
        while ((pos = body.find(';', last_pos)) != std::string::npos) {
            decls.push_back(body.substr(last_pos, pos - last_pos));
            last_pos = pos + 1;
        }
        
        for (auto& decl : decls) {
            decl = std::regex_replace(decl, std::regex(R"(//[^\n]*)"), "");
            decl = std::regex_replace(decl, std::regex(R"(/\*.*?\*/)", std::regex_constants::extended), "");
            decl = std::regex_replace(decl, std::regex(R"(\[\[[^\]]*\]\])"), "");
            
            while (!decl.empty() && std::isspace(decl.back())) decl.pop_back();
            while (!decl.empty() && std::isspace(decl.front())) decl.erase(0, 1);
            
            if (decl.empty()) continue;
            if (decl[0] == '#') continue;
            if (decl.find('(') != std::string::npos || decl.find(')') != std::string::npos) continue;
            
            static const std::vector<std::string> skip_keywords = {
                "using", "typedef", "friend", "public:", "private:", "protected:", "class", "struct", "enum"
            };
            bool skip = false;
            for (const auto& keyword : skip_keywords) {
                if (decl.find(keyword) != std::string::npos) {
                    skip = true;
                    break;
                }
            }
            if (skip) continue;
            
            FieldInfo f = parse_field(decl);
            if (!f.name.empty() && !f.type.empty()) {
                fields.push_back(f);
            }
        }
        
        generate_lombok_header(filepath, struct_name, fields, has_getter, has_setter, has_builder, has_tostring, has_equals_hash);
    }
}

// ─── rest_client sidecar generation ─────────────────────────────────────────

struct MethodParam {
    std::string type;  // e.g. "int", "examples::model::User"
    std::string name;  // e.g. "id", "user"
};

struct RestMethodInfo {
    std::string http_verb;   // get / post / put / del / patch
    std::string path;        // e.g. "/api/users/{id}"
    std::string return_type; // e.g. "novaboot::ResponseEntity<examples::model::User>"
    std::string method_name; // e.g. "get_user"
    std::vector<MethodParam> params;
    bool returns_void_entity = false; // ResponseEntity<void>
};

// Extract the inner quoted string from [[=novaboot::web::get{"/api/users/{id}"}]]
std::string extract_path_from_annotation(const std::string& ann) {
    auto q1 = ann.find('"');
    if (q1 == std::string::npos) return "";
    auto q2 = ann.find('"', q1 + 1);
    if (q2 == std::string::npos) return "";
    return ann.substr(q1 + 1, q2 - q1 - 1);
}

// Parse a parameter list string like "int id, examples::model::User user"
std::vector<MethodParam> parse_param_list(const std::string& raw) {
    std::vector<MethodParam> out;
    // Split on commas, but respect nested <>
    std::string cur;
    int depth = 0;
    for (char c : raw) {
        if (c == '<') depth++;
        else if (c == '>') depth--;
        else if (c == ',' && depth == 0) {
            // trim
            while (!cur.empty() && std::isspace(cur.front())) cur.erase(0, 1);
            while (!cur.empty() && std::isspace(cur.back())) cur.pop_back();
            if (!cur.empty()) {
                // last word = name, rest = type
                int i = (int)cur.size() - 1;
                while (i >= 0 && (std::isalnum(cur[i]) || cur[i] == '_')) i--;
                std::string pname = cur.substr(i + 1);
                std::string ptype = cur.substr(0, i + 1);
                while (!ptype.empty() && std::isspace(ptype.back())) ptype.pop_back();
                if (!pname.empty() && !ptype.empty())
                    out.push_back({ptype, pname});
            }
            cur.clear();
            continue;
        }
        cur += c;
    }
    // last param
    while (!cur.empty() && std::isspace(cur.front())) cur.erase(0, 1);
    while (!cur.empty() && std::isspace(cur.back())) cur.pop_back();
    if (!cur.empty()) {
        int i = (int)cur.size() - 1;
        while (i >= 0 && (std::isalnum(cur[i]) || cur[i] == '_')) i--;
        std::string pname = cur.substr(i + 1);
        std::string ptype = cur.substr(0, i + 1);
        while (!ptype.empty() && std::isspace(ptype.back())) ptype.pop_back();
        if (!pname.empty() && !ptype.empty())
            out.push_back({ptype, pname});
    }
    return out;
}

void generate_rest_client_sidecar(const std::string& filepath,
                                   const std::string& class_name,
                                   const std::string& interface_header,
                                   const std::vector<RestMethodInfo>& methods) {
    fs::path header_path(filepath);
    // Sidecar is named after the source file's stem: user_service_client.client.h
    std::string stem = header_path.stem().string();
    fs::path output_path = header_path.parent_path() / (stem + ".client.h");

    std::ofstream out(output_path);
    if (!out.is_open()) {
        std::cerr << "novaboot-scanner rest_client error: Could not write to " << output_path << "\n";
        return;
    }

    out << "// ── AUTO-GENERATED by novaboot-scanner (REST Client Codegen) ── DO NOT EDIT ──\n";
    out << "#pragma once\n\n";
    out << "#include \"" << header_path.filename().string() << "\"\n";
    out << "#include \"novaboot/client/rest_client.h\"\n";
    out << "#include \"novaboot/router/json.h\"\n";
    out << "#include <string>\n\n";

    out << "class " << class_name << "Impl : public " << class_name << " {\n";
    out << "public:\n";
    out << "    explicit " << class_name << "Impl(std::unique_ptr<novaboot::client::RestClient> c)\n";
    out << "        : client_(std::move(c)) {}\n\n";

    for (const auto& m : methods) {
        // Signature
        out << "    " << m.return_type << " " << m.method_name << "(";
        for (size_t i = 0; i < m.params.size(); ++i) {
            out << m.params[i].type << " " << m.params[i].name;
            if (i + 1 < m.params.size()) out << ", ";
        }
        out << ") override {\n";

        // Build path — substitute {param} for int-like params, leave body params out
        // Identify which params are path params vs body param
        // Path params: appear as {name} in path. Body param: the remaining one.
        std::string path = m.path;
        std::string body_param;
        std::vector<std::string> path_params;
        for (const auto& p : m.params) {
            std::string placeholder = "{" + p.name + "}";
            if (path.find(placeholder) != std::string::npos) {
                path_params.push_back(p.name);
            } else {
                body_param = p.name;
            }
        }

        // Build runtime path expression
        // Replace {name} in the literal with " + std::to_string(name) + "
        std::string path_expr = "\"" + path + "\"";
        for (const auto& pp : path_params) {
            std::string placeholder = "{" + pp + "}";
            std::string replacement = "\" + std::to_string(" + pp + ") + \"";
            size_t pos = 0;
            while ((pos = path_expr.find(placeholder, pos)) != std::string::npos) {
                path_expr.replace(pos, placeholder.size(), replacement);
                pos += replacement.size();
            }
        }
        // Clean up trailing + ""
        const std::string trail = " + \"\"";
        if (path_expr.size() >= trail.size() &&
            path_expr.substr(path_expr.size() - trail.size()) == trail)
            path_expr = path_expr.substr(0, path_expr.size() - trail.size());
        // Clean up leading "" +
        const std::string prefix = "\"\" + ";
        if (path_expr.substr(0, prefix.size()) == prefix)
            path_expr = path_expr.substr(prefix.size());

        // Emit the HTTP call
        if (m.http_verb == "get") {
            out << "        auto resp = client_->get(" << path_expr << ");\n";
        } else if (m.http_verb == "del") {
            out << "        auto resp = client_->del(" << path_expr << ");\n";
        } else if (m.http_verb == "post") {
            if (body_param.empty()) {
                out << "        auto resp = client_->post(" << path_expr << ", \"\");\n";
            } else {
                out << "        auto resp = client_->post(" << path_expr << ", novaboot::json::serialize(" << body_param << "));\n";
            }
        } else if (m.http_verb == "put") {
            if (body_param.empty()) {
                out << "        auto resp = client_->put(" << path_expr << ", \"\");\n";
            } else {
                out << "        auto resp = client_->put(" << path_expr << ", novaboot::json::serialize(" << body_param << "));\n";
            }
        } else if (m.http_verb == "patch") {
            if (body_param.empty()) {
                out << "        auto resp = client_->patch(" << path_expr << ", \"\");\n";
            } else {
                out << "        auto resp = client_->patch(" << path_expr << ", novaboot::json::serialize(" << body_param << "));\n";
            }
        }

        // Emit deserialization and return
        if (m.returns_void_entity) {
            out << "        return " << m.return_type << "::status(resp.status_code);\n";
        } else {
            // strip the outer ResponseEntity<...> to get the inner body type
            const std::string re_prefix = "novaboot::ResponseEntity<";
            std::string inner = m.return_type;
            if (inner.substr(0, re_prefix.size()) == re_prefix) {
                inner = inner.substr(re_prefix.size(), inner.size() - re_prefix.size() - 1);
            }
            out << "        auto body = novaboot::json::deserialize<" << inner << ">(resp.body);\n";
            out << "        return " << m.return_type << "::status(resp.status_code, std::move(body));\n";

        }

        out << "    }\n\n";
    }

    out << "private:\n";
    out << "    std::unique_ptr<novaboot::client::RestClient> client_;\n";
    out << "};\n";

    std::cout << "novaboot-scanner rest_client: Generated sidecar " << output_path << "\n";
}

void process_rest_client(const std::string& filepath, const std::string& content) {
    // Match: class [[=novaboot::web::rest_client{"url","proto"}]] ClassName {
    // C++26 syntax: the annotation sits between 'class' and the class name
    std::regex rc_class_regex(
        R"((?:class|struct)\s+\[\[\s*=\s*(?:novaboot\s*::\s*web\s*::\s*)?rest_client\s*\{[^}]*\}\s*\]\]\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\{)"
    );

    // [[=novaboot::web::get{"/path"}]]
    std::regex method_ann_regex(
        R"(\[\[\s*=\s*(?:novaboot\s*::\s*web\s*::\s*)?(get|post|put|del|patch|delete)\s*\{\s*("[^"]*")\s*\}\s*\]\])"
    );

    // virtual ReturnType method_name(params...) = 0;
    // Use a multiline-aware match; exclude lines with ~ClassName (destructor)
    std::regex virtual_method_regex(
        R"(virtual\s+(novaboot::[a-zA-Z_][a-zA-Z0-9_:<>, ]*?)\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(([^)]*)\)\s*=\s*0\s*;)"
    );

    auto cls_begin = std::sregex_iterator(content.begin(), content.end(), rc_class_regex);
    auto cls_end   = std::sregex_iterator();

    for (auto it = cls_begin; it != cls_end; ++it) {
        std::smatch cm = *it;
        std::string class_name = cm[1].str();

        // Extract the class body
        size_t start = cm.position(0) + cm.length();
        int depth = 1;
        size_t end = start;
        while (end < content.size() && depth > 0) {
            if (content[end] == '{') depth++;
            else if (content[end] == '}') depth--;
            end++;
        }
        std::string body = content.substr(start, (end - 1) - start);

        // Walk the body collecting (annotation, virtual method) pairs
        std::vector<RestMethodInfo> methods;

        std::sregex_iterator ann_it(body.begin(), body.end(), method_ann_regex);
        std::sregex_iterator ann_end;
        for (; ann_it != ann_end; ++ann_it) {
            std::smatch am = *ann_it;
            std::string verb = am[1].str();
            if (verb == "delete") verb = "del";
            std::string path = am[2].str();
            // Strip surrounding quotes
            if (path.size() >= 2 && path.front() == '"') path = path.substr(1, path.size() - 2);

            // Find the next virtual method after this annotation
            size_t ann_end_pos = am.position(0) + am.length();
            std::string after_ann = body.substr(ann_end_pos);
            std::smatch mm;
            if (!std::regex_search(after_ann, mm, virtual_method_regex)) continue;

            RestMethodInfo info;
            info.http_verb   = verb;
            info.path        = path;
            info.return_type = mm[1].str();
            info.method_name = mm[2].str();
            info.params      = parse_param_list(mm[3].str());

            // Trim return_type whitespace
            while (!info.return_type.empty() && std::isspace(info.return_type.front()))
                info.return_type.erase(0, 1);
            while (!info.return_type.empty() && std::isspace(info.return_type.back()))
                info.return_type.pop_back();

            // Check if ResponseEntity<void>
            info.returns_void_entity =
                (info.return_type.find("ResponseEntity<void>") != std::string::npos);

            methods.push_back(std::move(info));
        }

        if (!methods.empty()) {
            // Compute a relative path for the #include of the interface header
            // (just use the absolute path; the generated sidecar is placed next to the .h)
            generate_rest_client_sidecar(filepath, class_name, filepath, methods);
        }
    }
}

struct ComponentInfo {
    std::string name;
    std::string filepath;
    std::string stereotype;
};

int main(int argc, char* argv[]) {
    std::vector<std::string> scan_dirs;
    std::string output_file = "di_registrations.cpp";

    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if ((arg == "--dir" || arg == "-d") && i + 1 < argc) {
            scan_dirs.push_back(argv[++i]);
        } else if ((arg == "--output" || arg == "-o") && i + 1 < argc) {
            output_file = argv[++i];
        }
    }
    if (scan_dirs.empty()) {
        scan_dirs.push_back(".");
    }

    std::vector<ComponentInfo> components;

    // Regex to match component annotations and extract class name:
    // Matches [[=novaboot::di::component{}]] or [[=component{}]] etc.
    // then handles optional whitespace, other annotations, comments, newlines
    // and finally struct/class Name
    std::regex component_regex(
        R"((?:(struct|class)\s+)?\[\[\s*=\s*(?:[a-zA-Z0-9_]+\s*::\s*)*(component|service|repository|controller_advice|rest_controller|controller|module_tag|sql_repository|cache_repository)\s*(?:\{[^{}]*\})?\s*\]\](?:\s|\[\[[^\]]*\]\]|/\*[^*]*\*/|//[^\n]*\n)*(?:(struct|class)\s+)?([a-zA-Z_][a-zA-Z0-9_]*))"
    );

    try {
        for (const auto& scan_dir : scan_dirs) {
            // Recursively walk the directory
            for (const auto& entry : fs::recursive_directory_iterator(scan_dir)) {
                if (!entry.is_regular_file()) continue;

                auto ext = entry.path().extension();
                if (ext == ".h" || ext == ".hpp" || ext == ".hxx" || ext == ".cpp" || ext == ".cc") {
                    // Read file content
                    std::ifstream file(entry.path());
                    if (!file.is_open()) continue;

                    std::string content((std::istreambuf_iterator<char>(file)),
                                         std::istreambuf_iterator<char>());

                    process_lombok(fs::absolute(entry.path()).string(), content);
                    process_rest_client(fs::absolute(entry.path()).string(), content);

                    auto words_begin = std::sregex_iterator(content.begin(), content.end(), component_regex);
                    auto words_end = std::sregex_iterator();

                    for (std::sregex_iterator i = words_begin; i != words_end; ++i) {
                        std::smatch match = *i;
                        std::string name = match[4].str();
                        std::string stereotype = match[2].str();
                        components.push_back({name, fs::absolute(entry.path()).string(), stereotype});
                    }
                }
            }
        }
    } catch (const std::exception& e) {
        std::cerr << "novaboot-scanner error: " << e.what() << "\n";
        return 1;
    }

    // Write output registrations file
    std::ofstream out(output_file);
    if (!out.is_open()) {
        std::cerr << "Failed to open output file: " << output_file << "\n";
        return 1;
    }

    out << "// ── AUTO-GENERATED by novaboot-scanner ── DO NOT EDIT ──\n";
    out << "// Generated at compile time by scanning components.\n\n";
    out << "#include \"novaboot/di/di.h\"\n";
    out << "#include \"novaboot/core/server.h\"\n";

    // Deduplicate headers
    std::vector<std::string> headers;
    for (const auto& comp : components) {
        if (std::find(headers.begin(), headers.end(), comp.filepath) == headers.end()) {
            headers.push_back(comp.filepath);
        }
    }

    for (const auto& header : headers) {
        out << "#include \"" << header << "\"\n";
    }

    out << "\nusing namespace novaboot::di;\n";
    out << "using namespace novaboot::data;\n\n";
    out << "// ── Compile-time validation ──────────────────────────────────────────────\n";
    out << "#ifdef __cpp_impl_reflection\n";
    for (const auto& comp : components) {
        if (comp.stereotype == "module_tag") {
            out << "static_assert(novaboot::di::detail::is_module_class(^^" << comp.name << "),\n";
            out << "    \"" << comp.name << " must be annotated with [[=novaboot::di::module_tag{}]]\");\n";
        } else {
            out << "static_assert(novaboot::di::detail::is_managed_component(^^" << comp.name << "),\n";
            out << "    \"" << comp.name << " must be annotated with [[=novaboot::di::component{}]] or a stereotype alias\");\n";
        }
    }
    out << "#endif // __cpp_impl_reflection\n\n";

    out << "// ── Registration function ────────────────────────────────────────────────\n";
    out << "void novaboot_di_register_all(novaboot::di::RootContainer& root) {\n";
    out << "#ifdef __cpp_impl_reflection\n";
    for (const auto& comp : components) {
        out << "    // " << comp.name << "\n";
        if (comp.stereotype == "module_tag") {
            out << "    register_module<" << comp.name << ">(root);\n\n";
        } else {
            out << "    root.register_component<" << comp.name << ">();\n\n";
        }
    }
    out << "#else\n";
    out << "    (void)root;\n";
    out << "#endif\n";
    out << "}\n\n";

    out << "void novaboot_web_register_all(novaboot::Server& app) {\n";
    out << "#ifdef __cpp_impl_reflection\n";
    for (const auto& comp : components) {
        if (comp.stereotype == "controller" || comp.stereotype == "rest_controller") {
            out << "    app.register_controller<" << comp.name << ">();\n";
        } else if (comp.stereotype == "controller_advice") {
            out << "    app.register_advice<" << comp.name << ">();\n";
        }
    }
    out << "#else\n";
    out << "    (void)app;\n";
    out << "#endif\n";
    out << "}\n";

    std::cout << "novaboot-scanner: Scanned " << scan_dirs.size() << " directories, found " << components.size() << " components, wrote to " << output_file << "\n";
    return 0;
}
