#include <iostream>
#include <fstream>
#include <regex>
#include <string>
#include <vector>
#include <filesystem>
#include <algorithm>

namespace fs = std::filesystem;

struct ComponentInfo {
    std::string name;
    std::string filepath;
    std::string stereotype;
};

int main(int argc, char* argv[]) {
    std::string scan_dir = ".";
    std::string output_file = "di_registrations.cpp";

    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if ((arg == "--dir" || arg == "-d") && i + 1 < argc) {
            scan_dir = argv[++i];
        } else if ((arg == "--output" || arg == "-o") && i + 1 < argc) {
            output_file = argv[++i];
        }
    }

    std::vector<ComponentInfo> components;

    // Regex to match component annotations and extract class name:
    // Matches [[=novaboot::di::component{}]] or [[=component{}]] etc.
    // then handles optional whitespace, other annotations, comments, newlines
    // and finally struct/class Name
    std::regex component_regex(
        R"((?:(struct|class)\s+)?\[\[\s*=\s*(?:novaboot\s*::\s*(?:di|web)\s*::\s*)?(component|service|repository|controller_advice|rest_controller|controller)\s*\{?\s*\}?\s*\]\](?:\s|\[\[[^\]]*\]\]|/\*[^*]*\*/|//[^\n]*\n)*(?:(struct|class)\s+)?([a-zA-Z_][a-zA-Z0-9_]*))"
    );

    try {
        // Recursively walk the directory
        for (const auto& entry : fs::recursive_directory_iterator(scan_dir)) {
            if (!entry.is_regular_file()) continue;

            auto ext = entry.path().extension();
            if (ext == ".h" || ext == ".hpp" || ext == ".hxx" || ext == ".cpp" || ext == ".cc") {
                // Read file content
                std::ifstream file(entry.path());
                if (!file.is_open()) continue;

                std::string content((std::istreambuf_iterator<char>(file)),
                                     std::istreambuf_iterator<char>());

                auto words_begin = std::sregex_iterator(content.begin(), content.end(), component_regex);
                auto words_end = std::sregex_iterator();

                for (std::sregex_iterator i = words_begin; i != words_end; ++i) {
                    std::smatch match = *i;
                    std::string name = match[4].str();
                    std::string stereotype = match[2].str();
                    components.push_back({name, fs::absolute(entry.path()).string(), stereotype});
                }
            }
        }
    } catch (const std::exception& e) {
        std::cerr << "novaboot-scanner error: " << e.what() << "\n";
        return 1;
    }

    // Write output registrations file
    std::ofstream out(output_file);
    if (!out.is_open()) {
        std::cerr << "Failed to open output file: " << output_file << "\n";
        return 1;
    }

    out << "// ── AUTO-GENERATED by novaboot-scanner ── DO NOT EDIT ──\n";
    out << "// Generated at compile time by scanning components.\n\n";
    out << "#include \"novaboot/di/di.h\"\n";
    out << "#include \"novaboot/core/server.h\"\n";

    // Deduplicate headers
    std::vector<std::string> headers;
    for (const auto& comp : components) {
        if (std::find(headers.begin(), headers.end(), comp.filepath) == headers.end()) {
            headers.push_back(comp.filepath);
        }
    }

    for (const auto& header : headers) {
        out << "#include \"" << header << "\"\n";
    }

    out << "\nusing namespace novaboot::di;\n\n";
    out << "// ── Compile-time validation ──────────────────────────────────────────────\n";
    out << "#ifdef __cpp_impl_reflection\n";
    for (const auto& comp : components) {
        out << "static_assert(novaboot::di::detail::is_managed_component(^^" << comp.name << "),\n";
        out << "    \"" << comp.name << " must be annotated with [[=novaboot::di::component{}]] or a stereotype alias\");\n";
    }
    out << "#endif // __cpp_impl_reflection\n\n";

    out << "// ── Registration function ────────────────────────────────────────────────\n";
    out << "void novaboot_di_register_all(novaboot::di::RootContainer& root) {\n";
    out << "#ifdef __cpp_impl_reflection\n";
    for (const auto& comp : components) {
        out << "    // " << comp.name << "\n";
        out << "    root.register_component<" << comp.name << ">();\n\n";
    }
    out << "#else\n";
    out << "    (void)root;\n";
    out << "#endif\n";
    out << "}\n\n";

    out << "void novaboot_web_register_all(novaboot::Server& app) {\n";
    out << "#ifdef __cpp_impl_reflection\n";
    for (const auto& comp : components) {
        if (comp.stereotype == "controller" || comp.stereotype == "rest_controller") {
            out << "    app.register_controller<" << comp.name << ">();\n";
        } else if (comp.stereotype == "controller_advice") {
            out << "    app.register_advice<" << comp.name << ">();\n";
        }
    }
    out << "#else\n";
    out << "    (void)app;\n";
    out << "#endif\n";
    out << "}\n";

    std::cout << "novaboot-scanner: Scanned " << scan_dir << ", found " << components.size() << " components, wrote to " << output_file << "\n";
    return 0;
}
